CREATE TABLE IF NOT EXISTS tag (
	tag VARCHAR(50) PRIMARY KEY,
	posts INT NOT NULL DEFAULT 0,
	followers INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tag_follow (
	tag VARCHAR(50) NOT NULL,
	user_id BIGINT NOT NULL REFERENCES "user"(id),
	PRIMARY KEY(tag, user_id)
);
